<?php
/**
 *
 * Initial version created 13-06-2018 / 03:52 PM
 *
 * @author Varun Sridharan <varunsridharan23@gmail.com>
 * @version 1.0
 * @since 1.0
 * @package
 * @link
 * @copyright 2018 Varun Sridharan
 * @license GPLV3 Or Greater (https://www.gnu.org/licenses/gpl-3.0.txt)
 */

namespace WPOnion\Modules\Customize\Control;

if ( ! defined( 'ABSPATH' ) ) {
	die;
}

if ( ! class_exists( '\WPOnion\Modules\Customize\Control\checkbox' ) ) {
	/**
	 * Class checkbox
	 *
	 * @package WPOnion\Modules\Customize_Control
	 * @author Varun Sridharan <varunsridharan23@gmail.com>
	 * @since 1.0
	 */
	class checkbox extends \WPOnion\Modules\Customize\control {
		/**
		 * type
		 *
		 * @var string
		 */
		public $type = 'wponion_field_checkbox';


		protected function field() {
			$field = parent::field(); // TODO: Change the autogenerated stub

			if ( isset( $field['attributes'] ) ) {
				unset( $field['attributes']['data-customize-setting-link'] );
			}
			return $field;
		}
	}
}
