<?php
/**
 *
 * Initial version created 12-06-2018 / 04:23 PM
 *
 * @author Varun Sridharan <varunsridharan23@gmail.com>
 * @version 1.0
 * @since 1.0
 * @package
 * @link
 * @copyright 2018 Varun Sridharan
 * @license GPLV3 Or Greater (https://www.gnu.org/licenses/gpl-3.0.txt)
 */

namespace WPOnion\Modules\Customizer\Control;

if ( ! defined( 'ABSPATH' ) ) {
	die;
}

if ( ! class_exists( '\WPOnion\Modules\Customizer\Control\Cloneable' ) ) {
	/**
	 * Class cloneable
	 *
	 * @package WPOnion\Modules\Customize_Control
	 * @author Varun Sridharan <varunsridharan23@gmail.com>
	 * @since 1.0
	 */
	class Cloneable extends \WPOnion\Modules\Customizer\Control {
		/**
		 * type
		 *
		 * @var string
		 */
		public $type = 'wponion_field_key_value';

		/**
		 * Renders HTML Output.
		 */
		public function render_content() {
			$fid                = $this->unique['unique'] . '[' . $this->options['id'] . ']';
			$this->before_field = '<input type="hidden" class="wponion_cloneable_value" data-customize-setting-link="' . $fid . '" value=""/>';
			parent::render_content(); // TODO: Change the autogenerated stub

		}

		/**
		 * Handles Elements Value.
		 *
		 * @return array|bool|mixed|object
		 */
		protected function el_value() {
			$is_decode = json_decode( $this->value(), true );

			if ( is_array( $is_decode ) ) {
				return $is_decode;
			}
			return false;
		}
	}
}
