<?php
/**
 *
 * Initial version created 21-05-2018 / 02:47 PM
 *
 * @author Varun Sridharan <varunsridharan23@gmail.com>
 * @version 1.0
 * @since 1.0
 * @package
 * @link
 * @copyright 2018 Varun Sridharan
 * @license GPLV3 Or Greater (https://www.gnu.org/licenses/gpl-3.0.txt)
 */

namespace WPOnion\Field;

if ( ! class_exists( '\WPOnion\Field\Button_Set' ) ) {
	class Button_Set extends Checkbox_Radio {
		protected function output() {
			$this->field['type'] = ( true === $this->data( 'multiple' ) ) ? 'checkbox' : 'radio';
			echo '<div class="wponion-button-group-container">';
			parent::output(); // TODO: Change the autogenerated stub
			echo '</div>';
		}

		protected function _element_html( $label_attr, $field_attr, $value, $attr, $options ) {
			return '<div class="wponion-checker wponion-button-group button ' . $this->data( 'inactive' ) . ' ' . $this->data( 'size' ) . '"><label ' . wponion_array_to_html_attributes( $label_attr ) . '>
				<input ' . $field_attr . ' ' . $this->checked( $value, $attr['value'], 'checked' ) . '  />' . $options['label'] . '
			</label></div>';
		}


		protected function js_field_args() {
			return array(
				'active'   => $this->data( 'active' ),
				'inactive' => $this->data( 'inactive' ),
			);
		}

		protected function field_default() {
			return $this->parse_args( array(
				'multiple' => false,
				'size'     => false,
				'active'   => 'button-primary',
				'inactive' => 'button-secondary',
			), parent::field_default() );
		}
	}
}
