<?php
/**
 *
 * Initial version created 30-05-2018 / 06:55 PM
 *
 * @author Varun Sridharan <varunsridharan23@gmail.com>
 * @version 1.0
 * @since 1.0
 * @package
 * @link
 * @copyright 2018 Varun Sridharan
 * @license GPLV3 Or Greater (https://www.gnu.org/licenses/gpl-3.0.txt)
 */

namespace WPOnion\Value;

if ( ! defined( 'ABSPATH' ) ) {
	die;
}

if ( ! class_exists( '\WPOnion\Value\gallery' ) ) {
	/**
	 * Class gallery
	 *
	 * @package WPOnion\Value
	 * @author Varun Sridharan <varunsridharan23@gmail.com>
	 * @since 1.0
	 */
	class gallery extends \WPOnion\Bridge\Value {
		/***
		 * in_loop
		 *
		 * @var bool
		 */
		protected $in_loop = false;

		/**
		 * current_loop
		 *
		 * @var int
		 */
		protected $current_loop = 0;

		/**
		 * Calls After its done.
		 */
		protected function init_class() {
			$this->value    = $this->explode( $this->value, ',' );
			$_field         = $this->field;
			$_field['type'] = 'image';
			foreach ( $this->value as $id => $image ) {
				$class = wponion_field_value_class( $_field );
				if ( class_exists( $class ) ) {
					$this->value[ $id ] = new $class( $_field, $image, array(
						'unique'    => $this->unique,
						'plugin_id' => $this->plugin_id(),
						'module'    => $this->module(),
					) );
				}
			}
		}

		/**
		 * @return bool
		 */
		public function has() {
			if ( $this->current_loop + 1 <= count( $this->value ) ) {
				$this->in_loop = true;
				return true;
			} elseif ( count( $this->value ) === $this->current_loop + 1 && 0 > count( $this->value ) ) {
				$this->in_loop = true;
				return true;
			} else {
				$this->in_loop = false;
				return false;
			}
		}

		/**
		 * @param null $path
		 * @param null $default
		 *
		 * @return false|mixed|\WPOnion\Bridge\Value
		 */
		public function get( $path = null, $default = null ) {
			if ( false !== $this->in_loop ) {
				if ( isset( $this->value[ $this->current_loop ] ) ) {
					$data = $this->value[ $this->current_loop ];
					$this->current_loop++;
					return $data;
				}
			}
			return parent::get( $path, $default ); // TODO: Change the autogenerated stub
		}
	}
}